# Fichier de configuration pour Nixpacks

providers = ["php", "node"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader", 
    "npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "heroku-php-apache2 public/"
